### PR TITLE
feat: Add contract verification to release pipeline addressing

### PR DESCRIPTION
**Pull request by bruhhgnik**
Addressing #240 
# Pull Request type
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Testing
- [ ] Other (please describe):

# What is the current behavior?
Currently, there is no verification that the ECIP contract is declared on networks before package release.

Issue Number: #240

# What is the new behavior?
- Added contract verification to release pipeline for both PyPI and NPM packages
- Verifies ECIP contract is declared on Sepolia and mainnnet before allowing release
- Verification only runs during release (tag push)

# Does this introduce a breaking change?
- [ ] Yes
- [x] No

# Other information
Contract verification is added to both:
- maturin.yml (PyPI release)
- wasm.yml (NPM release)

### CODE REVIEW

**Review by feltroidprime — CHANGES_REQUESTED** [review]
Create a .py script and run it from CI instead of having duplicate code.

**Comment by bruhhgnik** [comment]
> Create a .py script and run it from CI instead of having duplicate code.

I made the changes as been said

**Comment by bruhhgnik** [comment]
> Create a .py script and run it from CI instead of having duplicate code.

I made the above said changes, kindly check

**Comment by feltroidprime** [comment]
Simply format the script using black.

**Pull request merged**
